wip

diff --git a/.github/workflows/second-action.yml b/.github/workflows/second-action.yml
--- a/.github/workflows/second-action.yml
+++ b/.github/workflows/second-action.yml
@@ -17,6 +17,12 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: '18'
+      - name: Ensure lockfile exists
+        run: |
+          if [ ! -f package-lock.json ]; then
+           echo "package-lock.json is missing!"
+           exit 1
+          fi
       - name: Install Dependencies
         run: npm ci
       - name: Run Tests
